// Standalone reading companion generated from the candidate guide, not a second source.
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const escape = text => text.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const inline = text => escape(text).replace(/\[([^\]]+)\]\(method:([^)]+)\)/g,'<a href="glossaire.html#$2">$1</a>');
const style = `
*{box-sizing:border-box}body{margin:0;background:#f7f9fa;color:#16334b;font:17px/1.65 'Segoe UI',Arial,sans-serif}a{color:#11756f;text-underline-offset:3px}a:focus-visible,summary:focus-visible{outline:3px solid #976323;outline-offset:4px}header{border-top:7px solid #11756f;padding:28px max(24px,calc((100vw - 1220px)/2));background:white}header p{margin:6px 0}.eyebrow{font-size:13px;letter-spacing:2px;font-weight:700;color:#11756f}h1{font-size:34px;line-height:1.2;margin:14px 0}h2{font-size:24px;line-height:1.3}h3{font-size:21px}main{max-width:1220px;margin:28px auto;padding:0 24px}.layout{display:grid;grid-template-columns:240px minmax(0,1fr);gap:36px}.contents{align-self:start;position:sticky;top:20px;font-size:15px}.contents a{display:block;padding:8px 12px;border-radius:6px;text-decoration:none}.contents a[aria-current]{background:#d9eee9;font-weight:700}.contents strong{display:block;margin:12px}.article{min-width:0;background:white;border:1px solid #d9e2e5;border-radius:14px;padding:28px}.article>p{max-width:78ch}.article section{margin-top:32px}section:target,dt:target{background:#eaf3f1;scroll-margin-top:20px}.example{padding:18px;background:#eaf3f1;border-radius:10px}.note{color:#506476;font-size:14px}.cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.card{display:block;padding:22px;border:1px solid #cbd7df;border-radius:12px;background:white;text-decoration:none}.card h2{margin:0 0 10px}.card p{margin:0;color:#506476}.card:hover{border-color:#11756f}.visual img{display:block;width:100%;height:auto}.visual-zoom{overflow:auto;max-height:80vh}.visual-zoom img{display:block;width:1600px;max-width:none}summary{cursor:pointer;color:#11756f;padding:10px 0}details{margin:18px 0}.pager{display:flex;justify-content:space-between;flex-wrap:wrap;gap:14px;border-top:1px solid #d9e2e5;margin-top:32px;padding-top:20px;font-size:15px}.section-index{padding:16px 22px;background:#f2f6f5;border-radius:10px}.section-index a{display:block;margin:4px 0}dt{font-weight:700;margin-top:24px}dd{margin:4px 0}.button{display:inline-block;background:#173950;color:white;border-radius:8px;padding:12px 18px;margin:16px 0;text-decoration:none}@media(max-width:780px){.layout{grid-template-columns:1fr}.contents{position:static}.contents details{margin:0}.article{padding:20px}.cards{grid-template-columns:1fr}header{padding:22px}h1{font-size:28px}main{padding:0 16px}.contents a{padding:6px 12px}}@media print{.contents,.pager,header .note{display:none}.layout{display:block}.article{border:0;padding:0}body{background:white}}
`;

export async function renderMethodPreview(guide, output) {
  const folder=resolve(output,'methodologie');
  await mkdir(folder,{recursive:true});
  const chapters=guide.chapters;
  const shell=(title,body,inside=false)=>`<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} — FLOW</title><style>${style}</style></head><body><header><div class="eyebrow">FLOW ATLAS / MÉTHODOLOGIE DE TRANSFORMATION</div><h1>${escape(title)}</h1><p class="note">Édition préparée ${escape(guide.version)} · Aperçu non publié</p>${inside?'<a href="../methodologie-transformation.html">← Sommaire et parcours de lecture</a>':''}</header><main>${body}</main></body></html>`;
  const nav=current=>`<aside class="contents"><details open><summary>Sommaire de la méthode</summary><strong>Parcours de lecture</strong>${chapters.map((c,i)=>`${i===5?'<strong>Approfondir</strong>':''}<a href="${c.id}.html" ${c.id===current?'aria-current="page"':''}>${escape(c.title)}</a>`).join('')}<a href="glossaire.html" ${current==='glossary'?'aria-current="page"':''}>Glossaire méthodologique</a></details></aside>`;
  const goals=['Comprendre comment les dimensions se répondent et comment l’équipe travaille.','Relier problèmes, usages, capacités, organisation, données et solutions.','Préparer les choix avec l’équipe, la direction de programme et les sponsors.','Éprouver les fondations et construire des transitions soutenables.','Observer l’adoption, suivre les bénéfices et organiser la continuité.'];
  const home=`<p>Une vue d’ensemble, puis une question à la fois. Choisis une rubrique dans le sommaire ou suis le parcours de lecture proposé.</p><p><strong>Ce parcours organise la lecture, pas les étapes du programme.</strong> Dans le travail réel, les dimensions s’instruisent ensemble et les apprentissages conduisent à revenir sur les choix.</p><a class="button" href="methodologie/start.html">Commencer par la vue d’ensemble →</a><h2>Parcours de lecture</h2><div class="cards">${chapters.slice(0,5).map((c,i)=>`<a class="card" href="methodologie/${c.id}.html"><h2>${escape(c.title)}</h2><p>${goals[i]}</p></a>`).join('')}</div><h2>Approfondir</h2><div class="cards">${chapters.slice(5).map(c=>`<a class="card" href="methodologie/${c.id}.html"><h2>${escape(c.title)}</h2></a>`).join('')}<a class="card" href="methodologie/glossaire.html"><h2>Glossaire méthodologique</h2></a></div>`;
  await writeFile(resolve(output,'methodologie-transformation.html'),shell('Sommaire et parcours de lecture',home));
  for(const [index,c] of chapters.entries()) {
    const visual=c.visual?.overview_svg;
    const image=visual?`data:image/svg+xml;charset=utf-8,${encodeURIComponent(visual)}`:null;
    const content=`<article class="article"><p>${inline(c.intro)}</p><nav class="section-index" aria-label="Dans cette rubrique"><strong>Dans cette rubrique</strong>${c.sections.map((s,i)=>`<a href="#section-${i}">${escape(s.title)}</a>`).join('')}</nav>${image?`<figure style="margin:24px 0"><div class="visual"><img src="${image}" alt="${escape(c.visual.title)}"></div><details><summary>Lire le schéma en grand format</summary><div class="visual-zoom" tabindex="0"><img src="${image}" alt="${escape(c.visual.title)}"></div></details><figcaption class="note">${escape(c.visual.description)}</figcaption></figure>`:''}${c.sections.map((s,i)=>`<section id="section-${i}"><h2>${escape(s.title)}</h2><p>${inline(s.text)}</p>${s.example?`<p class="example">${inline(s.example)}</p>`:''}${s.detail?`<details><summary>Précisions et points d’attention</summary><p>${inline(s.detail)}</p></details>`:''}${s.url?`<a href="${escape(s.url)}">Consulter la référence</a>`:''}</section>`).join('')}<nav class="pager" aria-label="Parcours de lecture">${index>0?`<a href="${chapters[index-1].id}.html">← ${escape(chapters[index-1].title)}</a>`:'<a href="../methodologie-transformation.html">← Sommaire</a>'}${index<4?`<a href="${chapters[index+1].id}.html">Continuer : ${escape(chapters[index+1].title)} →</a>`:'<a href="../methodologie-transformation.html">Revenir au sommaire →</a>'}</nav></article>`;
    await writeFile(resolve(folder,c.id+'.html'),shell(c.title,`<div class="layout">${nav(c.id)}${content}</div>`,true));
  }
  await writeFile(resolve(folder,'glossaire.html'),shell('Glossaire méthodologique',`<div class="layout">${nav('glossary')}<article class="article"><p>Les notions utiles à la démarche et au modèle, sans extension automatique du métamodèle.</p><dl>${guide.glossary.terms.map(t=>`<dt id="${t.id}">${escape(t.label_fr||t.name)} · ${escape(t.name)}</dt><dd>${escape(t.definition)}</dd>`).join('')}</dl></article></div>`,true));
}
